---
namespace: vooon
name: config
version: 2.6.2
readme: README.md
description: |-
  A collection with modified config_template and other helpers we commonly use.

authors:
  - Vladimir Ermakov <vooon341@gmail.com>
  - Kevin Carter <kevin.carter@rackspace.com>
  - Jimmy McCrory <jimmy.mccrory@gmail.com>
  - Jean-Philippe Evrard <jean-philippe.evrard@rackspace.co.uk>
  - Logan V <logan2211@gmail.com>

license:
  - "Apache-2.0"

tags:
  - linux
  - tools

repository: "https://github.com/vooon/ansible-collections-vooon-config"
